version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
  

  ml_service:
    build:
      context: .
      dockerfile: ml_service/Dockerfile
    ports:
      - "4500:4500"

  databases:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pixel
      POSTGRES_DB: db_test
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"