services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    
    

  backend:
    build:
      context: .
      dockerfile: stockinventory/Dockerfile
      args:
        - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}"
    ports:
      - "8080:8080"
    
    volumes:
      - ~/.m2:/root/.m2
    

    
      
    depends_on:  # Ensure the database starts before the backend
      - databases

  ml_service:
    build:
      context: .
      dockerfile: ml_service/Dockerfile
    ports:
      - "4500:4500"


  databases:
    
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pixel
      POSTGRES_DB: gestion_stock_dev
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    