name: Deploiement sur le serveur

on:
  push:
    branches:
      - sprint1


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configuration SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
    
    - name: Deploiement
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}
        cd ~/gestion_stock
        touch deploy.txt
        echo "Pulling from GitHub" >> deploy.txt